spring.application.name=civicpulse-api
server.port=8081
spring.jackson.serialization.indent-output=true
spring.data.mongodb.database=sociosolve
spring.data.mongodb.uri=mongodb+srv://myAtlasDBUser:CivicPulse12345@myatlasclusteredu.fgsdf1x.mongodb.net/?appName=myAtlasClusterEDU